In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
matrix = np.array([[1,2],[3,4]])
print(matrix)

[[1 2]
 [3 4]]


In [4]:
matrix.ndim

2

In [5]:
matrix.shape

(2, 2)

In [6]:
matrix.size

4

In [7]:
matrix.dtype

dtype('int32')

In [8]:
matrix.itemsize

4

In [9]:
arrr = np.arange(5)

In [10]:
print(arrr)

[0 1 2 3 4]


/*arrays with ones and zeros*/

In [11]:
print(np.zeros(5))
print(np.ones(5))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


**creating arrays with random numbers**

In [12]:
np.random.rand(5)           #creates sample of random numbers between 0 and 1

array([0.53373165, 0.80946142, 0.13665018, 0.19492852, 0.62411648])

In [13]:
np.random.randn(5)

array([-0.28593127, -2.27861446,  0.1708166 , -0.68349919, -0.43454645])

In [15]:
np.random.randint(2,3,3)

array([2, 2, 2])

#array is like list

In [16]:
import numpy as np
arr = np.array([1,2,3,4])

In [17]:
print(arr[0])

1


In [18]:
print(arr[:])

[1 2 3 4]


In [19]:
print(arr[1:3])

[2 3]


In [20]:
print(arr[:3])

[1 2 3]


In [21]:
print(arr[1:])

[2 3 4]


In [22]:
#for multidymentional array:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [23]:
print(arr[1,3])

8


In [24]:
print(arr[0])

[1 2 3 4]


In [25]:
print(arr[0:])

[[1 2 3 4]
 [5 6 7 8]]


In [26]:
#arithmatics on arrays