# Welcome Everyone

In [1]:
import numpy as np

In [2]:
myarr = np.array([[1, 3, 4]], np.int64)

In [3]:
myarr[0,1]

3

In [4]:
myarr.shape

(1, 3)

In [5]:
myarr.dtype

dtype('int64')

In [6]:
myarr[0,1] = 45

In [7]:
myarr

array([[ 1, 45,  4]], dtype=int64)

# Array creation. Conversion from other python structures (eg: list, tuples etc.)

In [8]:
listarray = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [9]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
listarray.dtype

dtype('int32')

In [11]:
listarray.size

9

In [12]:
listarray.shape

(3, 3)

In [13]:
np.array({34,23,43})

array({34, 43, 23}, dtype=object)

# Intrinsic numpy array creation objects (e.g.: arrange, ones, zeros etc)

In [14]:
zeros = np.zeros((2,5))

In [15]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
zeros.dtype

dtype('float64')

In [17]:
zeros.shape

(2, 5)

In [18]:
zeros.size

10

In [22]:
rng = np.arange(15) # gives array from 0 to (n-1)

In [23]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [33]:
lspace = np.linspace(3,30,10)  #GIVES 10 EQUALLY LINEARLY SPACES ELEMENTS BETWEEN 3 TO 30

In [34]:
lspace

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30.])

In [43]:
emp = np.empty((4,6)) # gives random valued array which shape is: 4, 6

In [44]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        9.34609111e-307, 1.42413555e-306, 1.78019082e-306],
       [1.37959740e-306, 6.23057349e-307, 1.02360935e-306,
        1.69120416e-306, 1.78022342e-306, 6.23058028e-307],
       [1.06811422e-306, 9.45699680e-308, 1.11258854e-306,
        1.11261502e-306, 1.42410839e-306, 7.56597770e-307],
       [6.23059726e-307, 1.42419530e-306, 7.56599128e-307,
        1.78022206e-306, 8.34451503e-308, 1.42404727e-306]])

In [46]:
emp.shape

(4, 6)

In [47]:
emp.size

24

In [51]:
emp_like = np.empty_like(lspace) #array with the same shape and type as a given array.

In [52]:
emp_like

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30.])

In [55]:
ide = np.identity(45) #gives identity array shaped 45x45

In [56]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [60]:
arrr = np.arange(99)

In [61]:
arrr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [62]:
arrr.reshape(3,33)  #reshapes arrr from 1x99 to 3x33

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [63]:
arrr # will not be updated(reshaped)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [64]:
arrr = arrr.reshape(3,33)

In [65]:
arrr #updated now

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [68]:
arrr = arrr.ravel() #makes 1D array

In [69]:
arrr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [70]:
x = [[1,2,3], [4,5,6], [7,1,0]]
ar = np.array(x)

In [71]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [72]:
ar.sum(axis = 0)  #finds the sum of all the columns

array([12,  8,  9])

In [73]:
ar.sum(axis = 1)  #finds the sum of all the row

array([ 6, 15,  8])

In [74]:
ar.T  #makes transpose of the array(row becomes column, column becomes row)

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [75]:
for item in ar.flat: #gives itarator
    print(item)

1
2
3
4
5
6
7
1
0


In [76]:
ar.ndim #number of dimension

2

In [77]:
ar.size

9

In [78]:
ar.nbytes

36

In [79]:
one = np.array([1,3,4,634,2])


In [80]:
one.argmin()  #gives the index of minimum arg

0

In [81]:
one.argmax()  #gives the index of maximum arg

3

In [82]:
one.argsort()  #sorts the array and gives their indexes(primary) in an array

array([0, 4, 1, 2, 3], dtype=int64)

In [83]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [84]:
ar.argmin()

8

In [85]:
ar.argmax()

6

In [88]:
ar.argmax(axis=0)  #gives index of the max arg towards column(axis 0)

array([2, 1, 1], dtype=int64)

In [89]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [90]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [91]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [92]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [93]:
ar2 = np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [95]:
ar + ar2  #results like matrix summation

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [97]:
ar * ar2 #multiplications (*****not like matrices******)

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [99]:
np.sqrt(ar)  #element wise square root

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [100]:
ar.sum()

29

In [101]:
ar.min()

0

In [103]:
ar.max()

7

In [106]:
np.where(ar>5)  #gives the index of the condition in a tuple. note here index start from 0

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [107]:
np.count_nonzero(ar)

8

In [109]:
np.nonzero(ar) #gives indexes of all nonzero elements like(0,0), (0,1),(0,2) etc

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))